import Pkg
Pkg.update()
Pkg.add("DataFrames")
Pkg.add("Pluto")
Pkg.add("Flux")
Pkg.add("IJulia")
Pkg.add("PlutoUI")
Pkg.add("DifferentialEquations")
Pkg.add("SymPy")
Pkg.add("Plots")
Pkg.add("Luxor")
