#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    statusline_display_mode = false

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
name = 'lang#haskell'

[[layers]]
name = 'lang#scala'

[[layers]]
name = 'lang#vim'

[[layers]]
name = 'lang#rust'

[[layers]]
name = 'lang#c'

[[layers]]
name = 'lang#r'

[[layers]]
name = 'lang#julia'

[[layers]]
name = 'lang#python'

[[layers]]
name = 'git'

[[layers]]
name = 'lang#markdown'

[[layers]]
name = 'ui'

[[layers]]
name = 'lang#toml'

[[layers]]
name = 'lang#go'

[[layers]]
name = 'lang#html'

[[custom_plugins]]
name = 'jpalardy/vim-slime'

[[custom_plugins]]
name = 'meck/vim-brittany'

[[custom_plugins]]
name = 'zah/nim.vim'

[[custom_plugins]]
name = 'tpope/vim-markdown'

[[custom_plugins]]
name = 'junegunn/vim-easy-align'

[[custom_plugins]]
name = 'pbrisbin/vim-syntax-shakespeare'
